# app.yaml

runtime: python310
env: standard
entrypoint: gunicorn -b :$PORT core.wsgi:application

handlers:
- url: /.*
  script: auto

runtime_config:
  python_version: 3

env_variables:
  APPENGINE_URL: https://alpine-inkwell-387016.oa.r.appspot.com