# Generated by Django 4.1.7 on 2023-05-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_post_connected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_connected',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
    ]
