# Generated by Django 4.1.7 on 2023-05-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_post_connected_comment_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='post',
            name='memory_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
