# Generated by Django 4.1.7 on 2023-05-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='memory_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
