# Generated by Django 4.1.7 on 2023-05-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_memory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='memory_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
