# Generated by Django 4.1.7 on 2023-05-25 13:03

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True),
        ),
    ]
